[workspace]
members = [
    "src/engine",
    "src/framework",
    "src/server",
]

[profile.dev]
overflow-checks = true
panic = "unwind"

[profile.release]
lto = true
incremental = false
overflow-checks = false
panic = "unwind"

[profile.bench]
codegen-units = 1
overflow-checks = false
