concurrent = 1
check_interval = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "YourHostName"
  url = "https://gitlab.com/"
  token = "YourGitLabToken"
  executor = "shell"
  cache_dir = "/home/gitlab-runner/build-cache"
